# https://pysnowflake.readthedocs.io/en/latest/
FROM python:3.8.13-slim-bullseye

RUN python -m pip install --upgrade pip

RUN pip install pysnowflake
# snowflake_start_server --address=0.0.0.0 --port=8910

CMD ["snowflake_start_server","--address=0.0.0.0","--port=8910"]